version: '3'

services:

  activemq:
    build: ./activemq
    container_name: activemq
    networks:
      - mensageria
    ports:
      - "61616:61616"

  producer:
    build: .
    container_name: message-producer
    networks:
      - mensageria
    volumes:
      - ./producer:/app
    depends_on:
      - activemq
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616

  consumer:
    build: .
    container_name: message-consumer
    networks:
      - mensageria
    depends_on:
      - activemq
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616

networks:
  mensageria:
    driver: bridge
